name = "Beta Unleashed 2.0"
author = "DanyGames2014"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6f7cec52c7c39edaed65086dd5c7ad2e58175cd957fbc2a92a8c7adb3ad10701"

[versions]
fabric = "0.19.3"
minecraft = "b1.7.3"
unsup = "1.2.7"

[options]
acceptable-game-versions = ["b1.7.3"]
